### ISSUE TITLE
Changing to PATCH

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#230]
@dting 

Been doing some reading on PUT vs PATCH, wondering if might be worth the time to adjust some of our routes: [stackoverflow](http://stackoverflow.com/questions/28459418/rest-api-put-vs-patch-with-real-life-examples)

**Comment by dting** [comment]
I've done a bit of follow up reading on the subject. Seems like this won't be as simple as just changing PUT to PATCH if we want to do this correctly, however, PATCH seems more correct than PUT. I am a bit concerned that PATCH is still in a proposal state. The other option is that we change it so instead of doing partial updates, do entire resource updates.

I'll do some more reading and let you know if I come across anything useful.

**Comment by pdotsani** [comment]
Sounds good. I'll experiment with this in a branch and create a pull request for you to check out. I'll try out PATCH on some routes and go from there.

**Comment by dting** [comment]
We discussed this and decided to leave stuff as is for now.
